// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZv6axeP4x0HBwVKDXdgRFYT_wEsbD4sg',
    appId: '1:1039210901503:web:327798577921b97ed901ca',
    messagingSenderId: '1039210901503',
    projectId: 'to-do-app-9ea3a',
    authDomain: 'to-do-app-9ea3a.firebaseapp.com',
    storageBucket: 'to-do-app-9ea3a.appspot.com',
    measurementId: 'G-NL74XJKN99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeSaJttup8b-sVWpRa_4icqzdNhrchoe0',
    appId: '1:1039210901503:android:4542b7ad089c49b5d901ca',
    messagingSenderId: '1039210901503',
    projectId: 'to-do-app-9ea3a',
    storageBucket: 'to-do-app-9ea3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7FqFNhcJWOWmBQRv1pFt2Yw1U7bjgF7A',
    appId: '1:1039210901503:ios:f9bdc337f7008549d901ca',
    messagingSenderId: '1039210901503',
    projectId: 'to-do-app-9ea3a',
    storageBucket: 'to-do-app-9ea3a.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7FqFNhcJWOWmBQRv1pFt2Yw1U7bjgF7A',
    appId: '1:1039210901503:ios:cb5d445daaef74fad901ca',
    messagingSenderId: '1039210901503',
    projectId: 'to-do-app-9ea3a',
    storageBucket: 'to-do-app-9ea3a.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
